import {
  ControlActionItem,
  ScheduledAutomationItem,
  RecentControlActivityItem,
  ActionImpactMetrics
} from '../types/actions';

export const CENTRAL_CONTROL_ACTIONS: ControlActionItem[] = [
  {
    id: 'ACT-2026-901',
    action: 'Restart production-api-01 worker thread pool',
    type: 'Restart',
    resource: 'production-api-01',
    source: 'AWS',
    risk: 'Medium',
    requestedBy: 'AI Incident Correlator',
    createdTime: '15m ago',
    status: 'Pending',
    reason: 'Remediate CPU saturation and event loop blockage from auth crypto processing.',
    currentState: 'CPU: 78%, p99 latency: 180ms, Event loop delay: 84ms',
    expectedState: 'CPU: < 50%, p99 latency: < 70ms, Event loop delay: < 5ms',
    relatedAlertId: 'ALT-002: High CPU on production-api-01',
    relatedRecommendationId: 'REC-2026-001: Rightsize production-api-01 instance',
    relatedIncidentId: 'INC-PROD-API-001: Production API Degradation',
    impactPreview: 'Graceful rolling restart of 4 worker threads. Zero client connection drop; 2s per worker.',
    executionLog: [
      '[10:45:00 UTC] Action generated by AI Correlator engine.',
      '[10:45:05 UTC] Pre-flight health check verified production-api-02 is healthy and taking standby traffic.'
    ]
  },
  {
    id: 'ACT-2026-902',
    action: 'Flush and warm production-cache query buffer',
    type: 'Optimization',
    resource: 'production-cache',
    source: 'AWS',
    risk: 'Low',
    requestedBy: 'AI Recommendation Engine',
    createdTime: '30m ago',
    status: 'Approved',
    reason: 'Pre-warm auth tokens in Redis cache memory to offload database query pressure.',
    currentState: 'Cache memory: 52%, Hit ratio: 78.4%',
    expectedState: 'Cache memory: ~60%, Hit ratio: > 95.0%',
    relatedAlertId: 'ALT-003: Production database memory usage high',
    relatedRecommendationId: 'REC-2026-002: Enable query caching for production-cache',
    impactPreview: 'Background asynchronous pipeline warm-up. No disruption to active users.',
    executionLog: [
      '[10:30:12 UTC] Action approved by Demo Operator (KP).',
      '[10:30:15 UTC] Scheduled for execution in next sync cycle.'
    ]
  },
  {
    id: 'ACT-2026-903',
    action: 'Trigger thermal throttle & force cooling fan to 100% on EDGE-003',
    type: 'Remediation',
    resource: 'EDGE-003',
    source: 'Edge',
    risk: 'Medium',
    requestedBy: 'Edge Telemetry Daemon',
    createdTime: '10m ago',
    status: 'Pending',
    reason: 'Critical thermal alert ALT-001 breach: Core temperature reached 82°C (max safe 75°C).',
    currentState: 'Core Temp: 82.0°C, Fan PWM: 55%, Status: Critical',
    expectedState: 'Core Temp: < 70.0°C, Fan PWM: 100%, Status: Healthy',
    relatedAlertId: 'ALT-001: EDGE-003 temperature threshold exceeded',
    relatedRecommendationId: 'REC-2026-003: Cooling fan curve on EDGE-003',
    relatedIncidentId: 'INC-2026-802: EDGE-003 Thermal Breach',
    impactPreview: 'Overclocks PWM fan controller to 100% duty cycle and throttles non-essential discovery scans.',
    executionLog: [
      '[10:50:00 UTC] High temperature threshold exceeded on EDGE-003.',
      '[10:50:02 UTC] Automated safety proposal drafted by Edge Telemetry Daemon.'
    ]
  },
  {
    id: 'ACT-2026-904',
    action: 'Purge zombie worker task PID on docker-worker-02',
    type: 'Remediation',
    resource: 'docker-worker-02',
    source: 'Docker',
    risk: 'Low',
    requestedBy: 'Automation Scheduler',
    createdTime: '1 hour ago',
    status: 'Completed',
    reason: 'Cleanse orphaned zombie PID 4410 and free file descriptors in container namespace.',
    currentState: 'Zombie tasks: 12 PIDs, Thread contention: High',
    expectedState: 'Zombie tasks: 0 PIDs, Container healthy',
    relatedAlertId: 'ALT-006: Docker worker PID zombie task backlog',
    impactPreview: 'Surgically sends SIGKILL to orphaned sub-process without restarting host container.',
    executionLog: [
      '[09:40:00 UTC] Action approved and dispatched to Docker daemon.',
      '[09:40:02 UTC] SIGKILL sent to orphaned PID 4410.',
      '[09:40:05 UTC] Process cleaned. Status restored to Healthy.'
    ]
  },
  {
    id: 'ACT-2026-905',
    action: 'Scale Kubernetes ingress gateway HPA minReplicas to 4',
    type: 'Scaling',
    resource: 'k8s-ingress-gateway',
    source: 'Kubernetes',
    risk: 'Low',
    requestedBy: 'AI Correlator Engine',
    createdTime: '25m ago',
    status: 'Approved',
    reason: 'Relieve socket backlog queue delay (185ms) during morning peak client traffic.',
    currentState: 'Active pods: 2, Queue delay: 185ms',
    expectedState: 'Active pods: 4, Queue delay: < 30ms',
    relatedAlertId: 'ALT-004: Kubernetes ingress latency increased',
    relatedRecommendationId: 'REC-2026-005: Scale Kubernetes ingress gateway',
    relatedIncidentId: 'INC-PROD-API-001: Production API Degradation',
    impactPreview: 'Spawns 2 additional NGINX ingress pods across worker nodes in EKS cluster.',
    executionLog: [
      '[10:35:10 UTC] HPA update approved by Demo Operator (KP).'
    ]
  },
  {
    id: 'ACT-2026-906',
    action: 'Failover switch-core-rack-02 trunk to redundant spine',
    type: 'Configuration',
    resource: 'switch-core-rack-02',
    source: 'On-Premise',
    risk: 'High',
    requestedBy: 'Network Sentinel AI',
    createdTime: '40m ago',
    status: 'Pending',
    reason: 'Optical SFP+ transceiver CRC packet loss detected on primary trunk Te1/0/48 (1.8% packet drop).',
    currentState: 'Packet drop: 1.8%, Latency: 45ms',
    expectedState: 'Packet drop: 0.0%, Latency: < 2ms',
    relatedAlertId: 'ALT-005: Network switch packet loss detected',
    relatedIncidentId: 'INC-2026-804: Core Switch Rack 02 Packet Drops',
    impactPreview: 'Triggers BGP/LACP dynamic reroute. Brief 50ms sub-second packet reconvergence.',
    executionLog: [
      '[10:20:00 UTC] Sentinel detected sustained CRC error count > 100/sec on port Te1/0/48.',
      '[10:20:05 UTC] High-risk confirmation barrier required before execution.'
    ]
  },
  {
    id: 'ACT-2026-907',
    action: 'Downsize production-api-01 to t3.medium',
    type: 'Optimization',
    resource: 'production-api-01',
    source: 'AWS',
    risk: 'High',
    requestedBy: 'FinOps Optimization Daemon',
    createdTime: '2 hours ago',
    status: 'Approved',
    reason: 'Downsize overprovisioned instance to capture $82/month recurring savings.',
    currentState: 'Instance: t3.large ($148/mo), RAM: 8GB (42% utilized)',
    expectedState: 'Instance: t3.medium ($66/mo), Projected savings: $82/mo',
    relatedRecommendationId: 'REC-2026-001: Rightsize production-api-01 instance',
    impactPreview: 'Requires blue-green instance replacement. Zero downtime via target group drainage.',
    executionLog: [
      '[08:42:15 UTC] Authorization granted by Demo Operator (KP).',
      '[08:42:20 UTC] Target group drain sequence queued.'
    ]
  }
];

export const CENTRAL_SCHEDULED_AUTOMATIONS: ScheduledAutomationItem[] = [
  {
    id: 'SCH-001',
    name: 'Hourly Edge Telemetry Flush & Log Rotation',
    description: 'Prunes local circular ring buffers and syncs compressed metric blobs to central storage.',
    frequency: 'Every 1 hour',
    nextRun: 'In 18 minutes',
    lastRun: '42m ago',
    status: 'Active',
    resourcesCovered: ['EDGE-001', 'EDGE-002', 'EDGE-003', 'EDGE-004'],
    executionType: 'Edge Autonomous Daemon'
  },
  {
    id: 'SCH-002',
    name: 'Daily Aurora Database Vacuum & Index Optimization',
    description: 'Analyzes query planner statistics and reindexes hot tables to optimize buffer hit ratios.',
    frequency: 'Daily at 02:00 UTC',
    nextRun: 'In 15 hours',
    lastRun: '9 hours ago',
    status: 'Active',
    resourcesCovered: ['production-db'],
    executionType: 'AWS RDS Maintenance Task'
  },
  {
    id: 'SCH-003',
    name: 'Kubernetes Pod Memory Leak Sentinel Sweep',
    description: 'Scans for anomalous heap growth trends across container namespaces and restarts leaking workers.',
    frequency: 'Every 30 minutes',
    nextRun: 'In 6 minutes',
    lastRun: '24m ago',
    status: 'Active',
    resourcesCovered: ['k8s-api-cluster', 'docker-worker-01', 'docker-worker-02'],
    executionType: 'Kubernetes CronJob Controller'
  }
];

export const CENTRAL_RECENT_CONTROL_ACTIVITIES: RecentControlActivityItem[] = [
  {
    id: 'ACT-LOG-01',
    time: '8m ago',
    user: 'Demo Operator (KP)',
    action: 'Approved EC2 Rightsizing',
    resource: 'production-api-01',
    result: 'Completed'
  },
  {
    id: 'ACT-LOG-02',
    time: '22m ago',
    user: 'Demo Operator (KP)',
    action: 'Approved Ingress Gateway HPA Scale',
    resource: 'k8s-ingress-gateway',
    result: 'Completed'
  },
  {
    id: 'ACT-LOG-03',
    time: '1h ago',
    user: 'Automation Daemon',
    action: 'Purged zombie worker task PID',
    resource: 'docker-worker-02',
    result: 'Completed'
  },
  {
    id: 'ACT-LOG-04',
    time: '2h ago',
    user: 'Security Guard',
    action: 'Blocked unauthorized public port bind',
    resource: 'EDGE-002',
    result: 'Rejected'
  }
];

export const CENTRAL_ACTION_IMPACT_METRICS: ActionImpactMetrics = {
  cpuReductionPercent: 18.5,
  monthlyCostSavings: 227,
  incidentReductionPercent: 42.0,
  availabilityPercent: 99.98
};
